# plumber.R generated by cloudrml

library(plumber)
library(jsonlite)

# Load the model
#* @model {{model_name}}
model <- readRDS("{{model_path}}")

#* @get /
#* @serializer html
function() {
  "<html><body><h1>Model '{{model_name}}' is live!</h1><p>Send a POST request to <code>/predict</code> with your data.</p></body></html>"
}

#* @post /predict
#* @param data The input data for prediction
function(req) {
  # Parse JSON into a data frame/tibble context
  input_data <- jsonlite::fromJSON(req$postBody)
  
  # Ensure input is a data frame for standard predict() calls
  if (!is.data.frame(input_data)) {
    input_data <- as.data.frame(input_data)
  }
  
  # Standard prediction call
  prediction <- tryCatch({
    predict(model, input_data)
  }, error = function(e) {
    list(error = e$message)
  })
  
  return(list(prediction = prediction))
}

#* @get /health
function() {
  list(status = "healthy", model = "{{model_name}}", timestamp = Sys.time())
}
